name: 'CI'

on:
  push:
    branches: 'main'
  pull_request:
    branches: '*'

permissions: {}

jobs:
  lint:
    name: 'pre-commit & prettier'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v7'
        with:
          persist-credentials: false

      - uses: 'actions/setup-python@v6'
        with:
          python-version: '3.14'

      - uses: 'pre-commit/action@v3.0.1'

      - uses: 'actions/setup-node@v6'
        with:
          node-version: '24'

      - uses: 'pnpm/action-setup@v6'
        with:
          version: '11.20.0'

      - run: 'pnpm install --frozen-lockfile'

      - run: 'pnpm run prettier:check'

  test:
    name: 'node --test'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v7'
        with:
          persist-credentials: false

      - uses: 'prefix-dev/setup-pixi@v0.8.8'

      - run: 'pixi install'

      - run: 'pixi run pnpm run build'

      - run: 'pixi run pnpm test'
