name: "Publish to npmjs.com"

on:
  release:
    types: ["published"]

permissions:
  id-token: "write"
  contents: "read"

jobs:
  publish:
    environment:
      name: "npmjs"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          persist-credentials: false

      - uses: "prefix-dev/setup-pixi@v0.8.8"

      - run: "pixi exec pnpm ci"
      - run: "pixi exec pnpm run build"
      # - run: "pixi exec pnpm test"
      - run: "pixi exec pnpm publish"
