name: "Test"

on:
  push:
    branches: "main"
  pull_request:
    branches: "*"

permissions: {}

jobs:
  test:
    name: "Javascript tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"
        with:
          persist-credentials: false

      - uses: "prefix-dev/setup-pixi@v0.8.8"

      - run: "pixi install"

      - run: "pixi run pnpm run build"

      - run: "pixi run pnpm test"
